name: ebook_app
description: "Erabook - The Number One Best Ebook Store & Reader Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  google_sign_in: ^6.2.1
  
  # PDF Viewer
  syncfusion_flutter_pdfviewer: ^24.1.41
  
  # Image Handling
  image_picker: ^1.0.7
  
  # State Management
  provider: ^6.0.5
  change_app_package_name: ^1.4.0
  
  # UI Utilities
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^2.7.0
  http: ^1.2.0
  
  # Storage and Data
  shared_preferences: ^2.2.0
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.5
  package_info_plus: ^4.2.0
  
  # UI Components
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  pdfx: ^2.6.0
  photo_view: ^0.14.0
  device_info_plus: ^9.1.2

  # Vector Math
  vector_math: ^2.1.4

  # Syncfusion Core
  syncfusion_flutter_core: ^24.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/books/