name: ebook_app
description: "Erabook - The Number One Best Ebook Store & Reader Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.0.5
  
  # UI Utilities
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Storage and Data
  shared_preferences: ^2.2.0
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.5
  package_info_plus: ^4.2.0
  
  # UI Components
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/