// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSZnJpIAjHTq1iOQmgkyURw1nZj7nGKTs',
    appId: '1:94890877862:web:964cf69e4bbcf27c99a567',
    messagingSenderId: '94890877862',
    projectId: 'booksharing-23036',
    authDomain: 'booksharing-23036.firebaseapp.com',
    storageBucket: 'booksharing-23036.firebasestorage.app',
    measurementId: 'G-ZBWY5QQR55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr4Apt608RDy5K4ovbXBmbHbLGx2BaZEY',
    appId: '1:94890877862:android:095f2a33f0c5713299a567',
    messagingSenderId: '94890877862',
    projectId: 'booksharing-23036',
    storageBucket: 'booksharing-23036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQJvIMXqL1aNp7wZTrX0YuEwuacviHHbg',
    appId: '1:94890877862:ios:ec96095bb61fbd3799a567',
    messagingSenderId: '94890877862',
    projectId: 'booksharing-23036',
    storageBucket: 'booksharing-23036.firebasestorage.app',
    iosBundleId: 'com.ihyaeforum.mayastoron',
  );
}
